<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Vero.Worker-309d0298-65fb-4a28-aefa-46281b1a8337</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.5.0" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" Version="2.2.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vero.Application\Vero.Application.csproj" />
    <ProjectReference Include="..\Vero.Infrastructure\Vero.Infrastructure.csproj" />
    <ProjectReference Include="..\Vero.Domain\Vero.Domain.csproj" />
  </ItemGroup>
</Project>
